// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhgem-P9Ousz4wxLKYN8AidZqf8_GkJ8s',
    appId: '1:818214270575:web:0229755521ef2a834dbf9a',
    messagingSenderId: '818214270575',
    projectId: 'cabutdulu-69',
    authDomain: 'cabutdulu-69.firebaseapp.com',
    storageBucket: 'cabutdulu-69.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnQyojhCJDLXXCGXCIUXcg9y-lGcpHfII',
    appId: '1:818214270575:android:0340631ec535df384dbf9a',
    messagingSenderId: '818214270575',
    projectId: 'cabutdulu-69',
    storageBucket: 'cabutdulu-69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxigFmPlLT_OYyVzUmKo-qPuMiq7s2LbU',
    appId: '1:818214270575:ios:0baad1fe31e46bf74dbf9a',
    messagingSenderId: '818214270575',
    projectId: 'cabutdulu-69',
    storageBucket: 'cabutdulu-69.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxigFmPlLT_OYyVzUmKo-qPuMiq7s2LbU',
    appId: '1:818214270575:ios:0baad1fe31e46bf74dbf9a',
    messagingSenderId: '818214270575',
    projectId: 'cabutdulu-69',
    storageBucket: 'cabutdulu-69.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhgem-P9Ousz4wxLKYN8AidZqf8_GkJ8s',
    appId: '1:818214270575:web:4bfc5ecaf76b97b14dbf9a',
    messagingSenderId: '818214270575',
    projectId: 'cabutdulu-69',
    authDomain: 'cabutdulu-69.firebaseapp.com',
    storageBucket: 'cabutdulu-69.firebasestorage.app',
  );

}